name:             "Owen Zhang"
description:      "Personal website of Owen Zhang"
title:            "Owen Zhang"
url:              http://owen6314.github.io
permalink:        pretty
highlighter:      rouge
maarkdown:        redcarpet 
plugins:
        - jekyll-feed
