name:             "Owen Zhang"
description:      "personal website"
title:            "Student"
url:              http://owen6314.github.io
permalink:        pretty
highlighter:      rouge
maarkdown:        redcarpet 
plugins:
        - jekyll-feed
