name:             "Qianrui Zhang"
description:      "Personal website of Qianrui Zhang"
title:            "Qianrui Zhang"
url:              http://owen6314.github.io
permalink:        pretty
highlighter:      rouge
maarkdown:        redcarpet 
plugins:
        - jekyll-feed
